### ISSUE TITLE
Error trying to generate open api doc

### ISSUE THREAD

**Issue by aberman** [bootprint/bootprint-openapi#69]
Just downloaded a fresh copy of bootprint and bootprint-openapi today and when I tried to generate docs, I got:

```
Loading bootprint-openapi 0.16.0
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.7.2

/usr/local/lib/node_modules/bootprint/node_modules/q/q.js:155
                throw e;
                ^
Error: Invalid mapping: {"generated":{"line":5,"column":17487},"source":"/usr/local/lib/node_modules/bootprint-openapi/node_modules/bootstrap/less/type.less","original":{"line":1,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/usr/local/lib/node_modules/bootprint/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/usr/local/lib/node_modules/bootprint/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
    at SourceMapOutput.add (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/source-map-output.js:88:42)
    at Element.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/element.js:42:12)
    at Selector.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/selector.js:104:21)
```

Looks like it could be a dependency version issue.

Any thoughts?

**Comment by gbegen** [comment]
Having the same problem here.

**Comment by nknapp** [comment]
This is due to https://github.com/bootprint/customize-engine-less/issues/1 and was introduced with `less@2.7.0`. Try reinstalling the dependencies and make sure that `customize-engine-less@0.2.4` is used. It binds the `less`-dependency to version 2.6.1
