### ISSUE TITLE
Exception Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by masterandrey** [bootprint/bootprint-openapi#74]
For the attached OpenAPI spec I'd got the exception:

[swagger.json.txt](https://github.com/bootprint/bootprint-openapi/files/361127/swagger.json.txt)

`Loading bootprint-openapi 0.17.0
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.7.2
[ '_docs/target/index.html',
  '_docs/target/main.css',
  '_docs/target/main.css.map' ]
<!DOCTYPE html>
<html>
<head>
    
/usr/local/lib/node_modules/html-inline/index.js:49
        if(path.isAbsolute(p)) {
                ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at fix (/usr/local/lib/node_modules/html-inline/index.js:49:17)
    at /usr/local/lib/node_modules/html-inline/index.js:36:24
    at Match._fn (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/index.js:100:17)
    at DestroyableTransform.write [as _transform] (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/html-select/lib/match.js:37:18)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Match.Pipeline._write (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/html-select/node_modules/stream-splicer/index.js:73:22)
    at Pipeline._write (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/html-select/node_modules/stream-splicer/index.js:73:22)
    at doWrite (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/usr/local/lib/node_modules/html-inline/node_modules/trumpet/node_modules/readable-stream/lib/_stream_writable.js:266:5)
`

**Comment by masterandrey** [comment]
Sorry, that's html-inline
