### ISSUE TITLE
exception TypeError: object is not a function (aka meaningful error-message on incorrect number of parameters)

### ISSUE THREAD

**Issue by masterandrey** [bootprint/bootprint-openapi#76]
Before that the bootprint-openapi worked fine.
For some time I used bootprint installed in docker container, and it still works (but I didn't reinstall it).
Local version in Ubuntu doesn't work anymore :(

```
`/usr/local/lib/node_modules/bootprint/node_modules/customize-watch/node_modules/customize/index.js:238
    return customizeModule(new Customize({ _metadata: _metadata }, _config, en
           ^
TypeError: object is not a function
    at Customize.load (/usr/local/lib/node_modules/bootprint/node_modules/customize-watch/node_modules/customize/index.js:238:12)
    at /usr/local/lib/node_modules/bootprint/node_modules/customize-watch/index.js:51:34
    at /usr/local/lib/node_modules/bootprint/node_modules/customize-watch/index.js:50:25
    at /usr/local/lib/node_modules/bootprint/node_modules/customize-watch/index.js:50:25
    at Recustomize.run (/usr/local/lib/node_modules/bootprint/node_modules/customize-watch/index.js:119:19)
    at Bootprint.generate (/usr/local/lib/node_modules/bootprint/index.js:37:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/bootprint/bin/bootprint.js:43:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`

`bootprint-openapi@0.17.0 /usr/local/lib/node_modules/bootprint-openapi
├── lodash@3.10.1
└── bootprint-json-schema@0.8.6 (bootprint-base@0.7.2)
`

`bootprint@0.8.5 /usr/local/lib/node_modules/bootprint
├── get-promise@1.4.0
├── q@1.4.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── clarify@1.0.5 (stack-chain@1.3.7)
├── lodash@3.10.1
├── debug@2.2.0 (ms@0.7.1)
├── trace@2.3.3 (stack-chain@1.3.7, async-hook@1.5.2)
├── js-yaml@3.6.1 (esprima@2.7.2, argparse@1.0.7)
├── customize-engine-less@0.2.5 (less@2.7.1)
├── customize-write-files@0.1.5 (q-io@1.13.2)
├── live-server@0.8.2 (object-assign@2.1.1, colors@1.1.2, event-stream@3.3.4, opn@4.0.2, send@0.14.1, faye-websocket@0.9.4, watchr@2.3.10, connect@2.30.2)
├── customize@0.8.4 (q-deep@1.0.3, jsonschema@1.1.0, minimatch@3.0.3, q-io@1.13.2, jsonschema-extra@1.2.0)
├── customize-engine-handlebars@0.7.0 (q-deep@1.0.3, promised-handlebars@1.0.6, handlebars@3.0.3)
└── customize-watch@0.5.4 (q-deep@1.0.3, q-io@1.13.2, customize@0.8.4, chokidar@1.6.0)
`
```

**Comment by nknapp** [comment]
Do you get any output like 

```
Loading bootprint-openapi 0.17.0
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.7.2
```

when you run bootprint? It seems like some bootprint-module is not exporting a function but an object.

**Comment by masterandrey** [comment]
I see no such lines.
The error is the first thing what I see.

BTW I reinstalled bootprint-openapi inside docker, I tried it on other machine - everything is fine.

So the problem on my machine only. 
I have no idea whats wrong - no experience with npm before.
I tried npm cache clean, reinstalled bootprint and bootprint-openapi - it doesn't help

**Comment by nknapp** [comment]
Try running `DEBUG=*:* bootprint openapi ...` and post the output here if you it does not contain any secrets.
Or send me a mail. I might have a look on Friday.

**Comment by masterandrey** [comment]
Oops, so stupid of me.
On my machine I removed by mistake 'openapi' part from sh-script.
Sorry for your time.

**Comment by nknapp** [comment]
Sounds like there sould be a more meaningful error-message if the number of parameters in incorrect.
